# Generated by Django 3.2.8 on 2021-10-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=55)),
                ('enrol_num', models.CharField(max_length=55, unique=True)),
                ('course_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=150)),
                ('session_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
