# Generated by Django 3.2.8 on 2021-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_auto_20211028_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksession',
            name='issued_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
